version: "3.5"

services:
  docker_php:
    container_name: docker_php
    build:
      context: ./php
      dockerfile: Dockerfile
      args:
        - LNMP_PHP_VERSION=${PHP_VERSION}
        - http_proxy
        - https_proxy
        - no_proxy
    tty: true
    restart: always
    expose:
      - "9000"
    ports:
      - "127.0.0.1:9000:9000"
    working_dir: ${APP_CODE_PATH_CONTAINER}
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      - ${DATA_PATH_HOST}/php/logs:/var/log/php-fpm
      - ${DATA_PATH_HOST}/php/php-fpm.d:/usr/local/etc/php-fpm.d
      - php-fpm:/var/run/php-fpm
      - mysqld:/var/run/mysqld
    depends_on:
      - docker_mysql
      - docker_redis
      - docker_mongo
    links:
      - docker_mysql:docker_mysql
      - docker_redis:docker_redis
      - docker_mongo:docker_mongo
  php-worker:
    container_name: docker_php-worker
    build:
      context: ./php-worker
      dockerfile: Dockerfile
      args:
        - LNMP_PHP_VERSION=${PHP_VERSION}
        - http_proxy
        - https_proxy
        - no_proxy
    tty: true
    restart: always
    working_dir: ${APP_CODE_PATH_CONTAINER}
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      - ${DATA_PATH_HOST}/php-worker/supervisord.d:/etc/supervisord.d
    depends_on:
      - docker_mysql
      - docker_redis
      - docker_mongo
    links:
      - docker_mysql:docker_mysql
      - docker_redis:docker_redis
      - docker_mongo:docker_mongo
  docker_nginx:
    container_name: docker_nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
        - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
        - http_proxy
        - https_proxy
        - no_proxy
    tty: true
    restart: always
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    working_dir: ${APP_CODE_PATH_CONTAINER}
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
      - php-fpm:/var/run/php-fpm
    depends_on:
      - docker_php
    links:
      - docker_php:docker_php
  docker_mysql:
    container_name: docker_mysql
    image: mysql:${MYSQL_VERSION}
    tty: true
    restart: always
    expose:
      - "3306"
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ${DATA_PATH_HOST}/mysql/conf.d:/etc/mysql/conf.d
      - ${DATA_PATH_HOST}/mysql/logs:/logs
      - ${DATA_PATH_HOST}/mysql/data:/var/lib/mysql
      - mysqld:/var/run/mysqld
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_520_ci
  docker_redis:
    container_name: docker_redis
    image: redis:latest
    tty: true
    restart: always
    expose:
      - "6379"
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ${DATA_PATH_HOST}/redis/data:/data
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
  docker_mongo:
    container_name: docker_mongo
    image: mongo:latest
    tty: true
    restart: always
    expose:
      - "27017"
    ports:
      - "${MONGODB_PORT}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - ${DATA_PATH_HOST}/mongod/db:/data/db
      - ${DATA_PATH_HOST}/mongod/configdb:/data/configdb
  laravel-echo-server:
    build:
      context: ./laravel-echo-server
      dockerfile: Dockerfile
    volumes:
      - ${DATA_PATH_HOST}/laravel-echo-server/laravel-echo-server.json:/usr/src/app/laravel-echo-server.json:ro
    ports:
      - "${LARAVEL_ECHO_SERVER_PORT}:6001"
    depends_on:
      - docker_redis
    links:
      - docker_redis:docker_redis
volumes:
  php-fpm:
    driver: ${VOLUMES_DRIVER}
  mysqld:
    driver: ${VOLUMES_DRIVER}